### PR TITLE
Fix download (now really)

### LINKED ISSUE #205: download results image throws error

### PR DESCRIPTION
**Pull request by fellnerse**
closes #205

### CODE REVIEW

File: components/DownloadPopup.vue [hunk 1]
```diff
@@ -1,14 +1,18 @@
...
     <v-row justify="center">
       <div class="cta my-md-4">
         <div class="text-h3 font-weight-bold pb-4">
           Download all Graphs at once!
         </div>
-        <div class="text-body-1">Currently for free! <br /></div>
-        <v-dialog v-model="dialog" width="500">
+        <div class="text-body-1 pb-2">All for free, just for you ❤️️</div>
+        <div class="text-body-2 pb-4">
+          You might want to wait until the <b>Word Cloud</b> is finished
```
Comment (PKehnel) [inline components/DownloadPopup.vue:10]: Please wait until

File: components/DownloadPopup.vue [hunk 2]
```diff
@@ -79,43 +87,65 @@ import { downloadBase64File } from "~/functions/utils";
...
         value: "1",
       });
 
-      let canvas = html2canvas(this.results.$refs.graphs, {
-        scrollX: 0,
-        scrollY: -window.scrollY,
-        onclone: function (clonedDoc) {
-          let nonVisibleStuff = clonedDoc.querySelectorAll(
-            ".only-visible-to-html2canvas"
+      let a = () => {
```
Comment (PKehnel) [inline components/DownloadPopup.vue:106]: what is **a**?

**Review by PKehnel — CHANGES_REQUESTED** [review]
Download looks really good. 
Maybe set the download button to "deactive" until the wordcloud is finished? 
Most people will not scroll down immediately to download, so this maybe isnt a problem in the normal use case. Just the wording is a little unclear it feels.

**Review by PKehnel — APPROVED** [review]

**Comment by PKehnel** [comment]
Ich würde zwar den Satz:
"You might want to wait until the Word Cloud is finished arranging."
weglassen oder sagen das man muss, aber ansonsten passts. 
So wirkt es so unklar, war passiert wenn man es nicht macht und wann ist sie fertig? Naja
